import { fireEvent, render, screen } from '@testing-library/react';
import React from 'react';
import ActivityPanel from '../../../components/ui/ActivityPanel';
import activity from '../../../data/activity.json';

// The snapshot is regenerated by CI, so every expectation derives from the
// data file rather than hard-coding numbers that go stale on the next build.
describe('ActivityPanel', () => {
  it('renders the headline contribution total from the snapshot', () => {
    render(<ActivityPanel />);
    expect(
      screen.getByText(
        `${activity.calendar.total.toLocaleString('en-US')} contributions in the last year`
      )
    ).toBeInTheDocument();
  });

  it('labels the calendar for assistive tech and hides the cells', () => {
    const { container } = render(<ActivityPanel />);
    const svg = screen.getByRole('img');
    expect(svg).toHaveAttribute(
      'aria-label',
      expect.stringContaining('contribution calendar')
    );
    const cells = container.querySelectorAll('.activity-cell');
    const dayCount = activity.calendar.weeks.reduce(
      (sum, week) => sum + week.length,
      0
    );
    expect(cells).toHaveLength(dayCount);
    expect(cells[0]).toHaveAttribute('aria-hidden', 'true');
  });

  it('renders the three metric tiles with values from the snapshot', () => {
    render(<ActivityPanel />);
    const { commits, mergedPRs, linesAdded, linesDeleted } = activity.metrics;
    expect(screen.getByText('commits')).toBeInTheDocument();
    expect(screen.getByText('prs merged')).toBeInTheDocument();
    expect(screen.getByText('lines changed')).toBeInTheDocument();
    // The precise values ride the tile tooltips even when the display value
    // is compacted.
    expect(
      screen.getByTitle(`${commits.toLocaleString('en-US')} commits`)
    ).toBeInTheDocument();
    expect(
      screen.getByTitle(`${mergedPRs.toLocaleString('en-US')} prs merged`)
    ).toBeInTheDocument();
    expect(
      screen.getByTitle(
        `${(linesAdded + linesDeleted).toLocaleString('en-US')} lines changed`
      )
    ).toBeInTheDocument();
  });

  it('shows a tooltip for a hovered day and clears it on leave', () => {
    const { container } = render(<ActivityPanel />);
    const cell = container.querySelector('.activity-cell') as SVGRectElement;
    fireEvent.mouseEnter(cell);
    const day = activity.calendar.weeks[0][0];
    const plural = day.count === 1 ? 'contribution' : 'contributions';
    expect(screen.getByRole('status')).toHaveTextContent(
      `${day.count} ${plural}`
    );
    fireEvent.mouseLeave(screen.getByRole('img'));
    expect(screen.queryByRole('status')).not.toBeInTheDocument();
  });

  it('dates the snapshot in the footer', () => {
    render(<ActivityPanel />);
    expect(screen.getByText(/^as of /)).toBeInTheDocument();
  });
});
